

INSERT INTO FARMS (NAME, FUNDS, DATE) VALUES ('Bamfurlong', 1000, 0);


INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME) VALUES ( 'Wheat', 20, 300, 20);


INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('small field', 2, 10);


INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('lower river', 0, 1, 1, 1);