

INSERT INTO FARMS (NAME, FUNDS, DATE) VALUES ('Bamfurlong', 1000, 0);
INSERT INTO FARMS (NAME, FUNDS, DATE) VALUES ('OldMcDonalds', 200, 0);
INSERT INTO FARMS (NAME, FUNDS, DATE) VALUES ('Underhill', 200, 0);
INSERT INTO FARMS (NAME, FUNDS, DATE) VALUES ('HighMill', 200, 0);


INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ( 'Wheat', 20, 300, 20, 35);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Corn', 20, 300, 20, 50);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Rye', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Rice', 20, 300, 20, 50);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Sunflowers', 20, 300, 20, 60);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Lavender', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Potatoes', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Cabbages', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Leeks', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Tomatoes', 20, 300, 20, 30);
INSERT INTO CROPS (NAME, PRICE, STOCK, GROWTIME, SELLPRICE) VALUES ('Carrots', 20, 300, 20, 30);


INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('small field', 2, 10);
INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('tiny field', 1, 5);
INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('medium field', 4, 20);
INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('large field', 8, 40);
INSERT INTO FIELD_TYPES (NAME, SIZE, COST) VALUES ('huge field', 16, 80);


INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('lower river', 0, 1, 1, 1);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('upper river', 0, 3, 4, 1);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('downstream', 0, 3, 1, 2);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('hilly meadow', 0, 1, 3, 3);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('marshy meadow', 0, 2, 7, 3);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('flat meadow', 0, 3, 8, 4);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('just a field', 0, 5, 5, 4);
INSERT INTO FIELDS (NAME, TIMELEFT, FIELD_ID, CROP_ID, FARM_ID) VALUES ('field not found', 0, 2, 4, 4);